[graph]
targets = []

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
    "Apache-2.0 WITH LLVM-exception",
]

[advisories]
db-path = "~/.cargo/advisory-db"
yanked = "deny"
